kind: pipeline
name: default

steps:
  - name: zip
    image: alpine
    commands:
      - apk update && apk add zip
      - zip -r handler.zip *

  - name: deploy-lambda
    image: mesosphere/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: XXX
      AWS_SECRET_ACCESS_KEY:
        from_secret: XXX
      AWS_DEFAULT_REGION: ap-northeast-1
    commands:
      - aws lambda update-function-code --function-name helloWorld --zip-file fileb://./function.zip
